### ISSUE TITLE
Nethermind Merge interop tracker

### ISSUE THREAD

**Issue by MarekM25** [NethermindEth/nethermind#3461]
Tracking for [Merge Interop](https://hackmd.io/@tvanepps/amphora-milestones#Milestones)
PR and description: https://github.com/NethermindEth/nethermind/pull/3453

different interop [docs](https://github.com/NethermindEth/nethermind/tree/themerge/amphora)

- [x] M0: Implementation started
- [x]  M1: Spec Implemented
  - [x] Test vectors https://notes.ethereum.org/@9AeMAlpyQYaAAyuj47BzRw/rkwW3ceVY
  - [x] (Experimental): run against mergemock https://github.com/protolambda/mergemock
- [x]  M2: 1-to-1 Interop (no transition) – One EL and one CL team pair off for basic interop testing
- [x]  M3: 1-to-1 Interop (with transition) – One EL and one CL team pair off for full interop testing
- [x]  M4: Many-to-Many Interop – 2 or more EL and CL teams perform interop testing
        (Geth, Nethermind, Lighthouse, Lodestar/Nimbus/Teku/Prysm?)
- [x]  M5: All-to-All persistent devnet – All ready EL and CL teams create a long-lived devnet

</br>

- [x] M2 Nethermind - Lighthouse
- [x] M2 Nethermind - Lodestar
- [x] M2 Nethermind - Nimbus
- [x] Nethermind - Prysm
- [x] M2 Nethermind - Teku
- [x] M3 Nethermind - Lighthouse
- [x] M3 Nethermind - Lodestar
- [x] M3 Nethermind - Nimbus
- [x] M3 Nethermind - Prysm
- [x] M3 Nethermind - Teku
- [x] M4 Nethermind - Besu
- [x] M4 Nethermind - Erigon
- [x] M4 Nethermind - EthereumJS
- [x] M4 Nethermind - Geth
- [x] M5 Nethermind - Geth
