### ISSUE TITLE
EIP-1955 Cliquey Upgrade Tracker

### ISSUE THREAD

**Issue by soc1c** [NethermindEth/nethermind#474]
ref https://github.com/goerli/eips-poa/issues/12 https://github.com/ethereum/EIPs/pull/1955

Cliquey is a proposed upgrade to Clique based networks, esp. Goerli.

### Review Spec

- [x] Please take time to review Cliquey Patch https://github.com/ethereum/EIPs/pull/1955

### Implement Upgrades

- [ ] Add `Cliquey` transition/config
- [ ] Implement EIP-1955 Cliquey proof-of-authority consensus protocol
- [ ] Consider activating it as default block 0 on new Clique networks

**Comment by tkstanczak** [comment]
@soc1c I agree with the point of being able to configure the initial list of the signers
Other changes are controversial until we run some simulation.

**Comment by soc1c** [comment]
Ideally, 1955 shouldn't be controversial. I'll rework the proposal based on all feedback received so far.

**Comment by soc1c** [comment]
Needs some work. :hourglass_flowing_sand:
