### ISSUE TITLE
Istanbul tracker

### ISSUE THREAD

**Issue by tkstanczak** [NethermindEth/nethermind#771]
Copied from Geth tracker by karalabe

https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1679.md

Accepted EIPs:
 - [x] EIP-152: Blake2 compression function F precompile #816
 - [x] EIP-1108: Reduce alt_bn128 precompile gas costs #814 
        need benchmarks for current implementation
 - [x] EIP-1344: ChainID opcode
 - [x] EIP-2028: Calldata gas cost reduction
 - [x] EIP-1884: Repricing for trie-size-dependent opcodes #815
 - [x] EIP-2200: Rebalance net-metered SSTORE gas cost #817
        confirm implementation

Maintenance
 - [x] add chainspec details

Probably Istanbul 2:

 - [ ] EIP-1057: ProgPoW, a Programmatic Proof-of-Work
 - [ ] EIP-1962: EC arithmetic and pairings with runtime definitions

Tentative Istanbul 2:

 - [ ] EIP-1702: Generalized account versioning scheme
 - [ ] EIP-663: Unlimited SWAP and DUP
 - [ ] EIP 1380: Reduced gas cost for call to self
 - [ ] EIP 1985: Sane limits for certain EVM parameters
 - [ ] EIP 2045: Particle gas costs for EVM opcodes
 - [ ] EIP 2046: Reduced gas cost for static calls made to precompiles
        based on EIP-1283 which is already implemented in Nethermind
