### ISSUE TITLE
Constantinople progress

### ISSUE THREAD

**Issue by tkstanczak** [NethermindEth/nethermind#93]
EIPs included in Constantinople:

- [x] EIP 145: Bitwise shifting instructions in EVM, #13 
- [x] EIP 1014: Skinny CREATE2, #15 
- [x] EIP 1052: EXTCODEHASH opcode, #16 
- [x] EIP 1283: Net gas metering for SSTORE without dirty maps, #17
- [x] EIP 1234: Constantinople Difficulty Bomb Delay and Block Reward Adjustment, #92

**Comment by tkstanczak** [comment]
implemented with tests wherever provided in spec, need to review the new blockchain tests in ethereum/test (assuming that the new opcodes are covered there extensively)

1283 - implementation uses some additional memory now to store original values, which can be improved by exposing first elements from change stacks in StorageProvider (either by using different data structure or by writing own stack implementation as the .NET stack only exposes peek and pop/push

**Comment by tkstanczak** [comment]
CREATE2 spec gives some options so need to confirm which one was implemented in other clients (should be enough to run etheruem/tests)

**Comment by tkstanczak** [comment]
difficulty bomb delay not tested so will only be tested with ethereum/tests
- [ ] add basic difficulty tests directly in Nethermind tests
